### ISSUE TITLE
Too strict service_id foreign key requirement

### ISSUE THREAD

**Issue by hbruch** [derhuerst/gtfs-via-postgres#16]
Currently, [calendar_dates.js ](https://github.com/derhuerst/gtfs-via-postgres/blob/master/lib/calendar_dates.js#L12) declares a foreign key constraint for column `service_id`.

According to the [GTFS spec](https://developers.google.com/transit/gtfs/reference#calendar_datestxt), this is not necessarily the case, as calendar_dates.service_id is _referencing calendar.service_id or ID_ 

This issue results in issues for some service optimized GTFS datasets.

**Comment by derhuerst** [comment]
> This issue results in issues for some service optimized GTFS datasets.

Are you talking about GTFS datasets that contain services which only occur within `calendar_dates`?

This doesn't affect the issue you're describing here, but FYI: https://github.com/google/transit/pull/278 was just merged.

**Comment by derhuerst** [comment]
I have published a fix as `gtfs-via-postgres@3.0.2`. 🎉
